---
apiVersion: v1
kind: Service
metadata:
  name: spring-pet-service
spec:
  type: NodePort
  selector:
    app: spring-pet  
  ports:
    - containerPort: 8080
      targetPort: 8080
      nodePort: 3305  
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: spring-pet  
  labels:
    app: spring-pet
spec:
  selector:
    matchlabels:
      app: spring-pet
  tempalte:
    metadata:
      lables:
        app: spring-pet
  replicas: 2
    spec:
      containers:
        - name: springpetclinic container
          image: "pvenkateswarrao/spring-pet:latest"
          ports:
            - containerPort: 8080  
      imagePullSecrets:
        - name: dockersecerts                  
  